2025-07-23 10:01:32,136 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-23 10:01:32,137 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-23 13:29:36,726 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-23 13:29:36,727 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-23 13:29:41,037 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-23 13:29:41,038 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 14:58:42,611 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 14:58:42,613 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 14:58:42,634 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 14:58:42,634 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:07:39,760 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:07:39,762 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:07:39,773 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:07:39,773 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:15:09,363 - werkzeug - INFO - 127.0.0.1 - - [24/Jul/2025 15:15:09] "[33mGET /api/admin/outages HTTP/1.1[0m" 404 -
2025-07-24 15:19:00,093 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:19:00,094 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:19:00,104 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:19:00,104 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:32:11,706 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:32:11,707 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:32:11,718 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:32:11,718 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:32:43,434 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:32:43,435 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:32:43,445 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:32:43,445 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:33:46,215 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:33:46,217 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:33:46,227 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:33:46,227 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:38:53,835 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:38:53,836 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:38:53,847 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:38:53,847 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-24 15:41:37,439 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-24 15:41:37,440 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-24 15:41:37,452 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.51:5000
2025-07-24 15:41:37,452 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-29 10:51:34,352 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-29 10:51:34,353 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 10:52:22,621 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-29 10:52:22,623 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 10:52:45,551 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-29 10:52:45,552 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 10:53:06,317 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-29 10:53:06,318 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 10:53:08,250 - app - WARNING - Model registration failed: No module named 'extensions'
2025-07-29 10:53:08,251 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 10:56:18,498 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:02:06,679 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:02:28,090 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:02:45,084 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:03:03,361 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:03:10,110 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:09:49,578 - app - WARNING - Blueprint registration failed: name 'init_auth_blueprint' is not defined
2025-07-29 11:44:30,042 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:45:51,521 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:46:19,223 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:46:27,356 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:47:10,717 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:48:01,698 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:48:10,645 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:52:53,710 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 11:53:16,240 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:06:34,369 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:08:13,120 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:08:21,415 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:09:02,378 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:09:56,455 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:13:00,927 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:14:16,051 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 13:14:16,136 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 14:09:01,987 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 14:10:40,647 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 14:10:48,470 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 14:56:32,818 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 14:56:51,952 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 15:16:22,602 - app - WARNING - Blueprint registration failed: name 'tickets_bp' is not defined
2025-07-29 15:18:02,372 - app - ERROR - Exception on /freshworks-linking/ [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:18:02,379 - app - ERROR - Exception on /freshworks-linking/api/mappings [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:18:08,485 - app - ERROR - Exception on /freshworks-linking/ [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:18:08,487 - app - ERROR - Exception on /freshworks-linking/api/mappings [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:18:20,183 - app - ERROR - Exception on /freshworks-linking/ [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:18:20,187 - app - ERROR - Exception on /freshworks-linking/api/mappings [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:22:49,237 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-29 15:22:49,238 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-29 15:22:49,542 - app - ERROR - Exception on /freshworks-linking/ [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:22:49,544 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:22:49] "[35m[1mGET /freshworks-linking/ HTTP/1.1[0m" 500 -
2025-07-29 15:22:54,204 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:22:54] "[32mGET / HTTP/1.1[0m" 302 -
2025-07-29 15:22:54,211 - app - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\Documents\yam\app\blueprints\auth\routes.py", line 59, in login
    if current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:22:54,212 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:22:54] "[35m[1mGET /login HTTP/1.1[0m" 500 -
2025-07-29 15:23:08,884 - app - ERROR - Exception on /api/activity/all [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:23:08,885 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:08] "[33mGET /api/admin/outages?all=true HTTP/1.1[0m" 404 -
2025-07-29 15:23:08,885 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:08] "[35m[1mGET /api/activity/all HTTP/1.1[0m" 500 -
2025-07-29 15:23:10,582 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:10] "[33mGET /api/admin/outages?all=true HTTP/1.1[0m" 404 -
2025-07-29 15:23:22,136 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:22] "[33mGET /api/admin/outages?all=true HTTP/1.1[0m" 404 -
2025-07-29 15:23:22,137 - app - ERROR - Exception on /api/activity/all [GET]
Traceback (most recent call last):
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\werkzeug\local.py", line 515, in _get_current_object
    return get_name(local())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\oscar.solis\AppData\Roaming\Python\Python310\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-07-29 15:23:22,140 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:22] "[35m[1mGET /api/activity/all HTTP/1.1[0m" 500 -
2025-07-29 15:23:22,400 - werkzeug - INFO - 127.0.0.1 - - [29/Jul/2025 15:23:22] "[33mGET /api/admin/outages?all=true HTTP/1.1[0m" 404 -
2025-07-30 08:55:51,983 - app - WARNING - Blueprint registration failed: name 'tickets_api_bp' is not defined
2025-07-30 14:10:31,685 - app - WARNING - Blueprint registration failed: name 'tickets_api_bp' is not defined
2025-07-30 14:11:52,775 - app - WARNING - Blueprint registration failed: name 'tickets_api_bp' is not defined
2025-07-31 15:31:12,219 - app - WARNING - Failed to start leaderboard timer service: cannot import name 'leaderboard_timer_service' from partially initialized module 'app.services.leaderboard_timer_service' (most likely due to a circular import) (C:\Users\oscar.solis\Documents\yam\app\services\leaderboard_timer_service.py)
2025-07-31 15:31:12,247 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:31:12,250 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-07-31 15:31:12,285 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:32:47,783 - app - WARNING - Failed to start leaderboard timer service: cannot import name 'leaderboard_timer_service' from partially initialized module 'app.services.leaderboard_timer_service' (most likely due to a circular import) (C:\Users\oscar.solis\Documents\yam\app\services\leaderboard_timer_service.py)
2025-07-31 15:32:47,810 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:32:47,814 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-07-31 15:32:47,842 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:32:47,864 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.45:5000
2025-07-31 15:32:47,864 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-31 15:32:49,654 - app - WARNING - Failed to start leaderboard timer service: cannot import name 'leaderboard_timer_service' from partially initialized module 'app.services.leaderboard_timer_service' (most likely due to a circular import) (C:\Users\oscar.solis\Documents\yam\app\services\leaderboard_timer_service.py)
2025-07-31 15:32:49,687 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:32:49,689 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-07-31 15:32:49,718 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:32:54,318 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:32:54] "GET /socket.io/?connection_id=socket_1754000976327_s2exhjmj8&timestamp=1754000976327&EIO=4&transport=polling&t=PXYdUtt HTTP/1.1" 200 -
2025-07-31 15:32:54,563 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:32:54] "POST /socket.io/?connection_id=socket_1754000976327_s2exhjmj8&timestamp=1754000976327&EIO=4&transport=polling&t=PXYdUym&sid=I8bltH46XHA9eBM4AAAA HTTP/1.1" 200 -
2025-07-31 15:32:54,627 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:32:54] "GET /socket.io/?connection_id=socket_1754000976327_s2exhjmj8&timestamp=1754000976327&EIO=4&transport=polling&t=PXYdUyn&sid=I8bltH46XHA9eBM4AAAA HTTP/1.1" 200 -
2025-07-31 15:32:54,634 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:32:54] "GET /socket.io/?connection_id=socket_1754000976327_s2exhjmj8&timestamp=1754000976327&EIO=4&transport=polling&t=PXYdV1c&sid=I8bltH46XHA9eBM4AAAA HTTP/1.1" 200 -
2025-07-31 15:32:54,937 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:32:54] "POST /socket.io/?connection_id=socket_1754000976327_s2exhjmj8&timestamp=1754000976327&EIO=4&transport=polling&t=PXYdV1c.0&sid=I8bltH46XHA9eBM4AAAA HTTP/1.1" 200 -
2025-07-31 15:33:30,316 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:33:30] "[33mGET /api/tickets/closures/today HTTP/1.1[0m" 404 -
2025-07-31 15:34:30,008 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:34:30] "[33mGET /api/tickets/closures/today HTTP/1.1[0m" 404 -
2025-07-31 15:35:19,955 - app - WARNING - Failed to start leaderboard timer service: cannot import name 'leaderboard_timer_service' from partially initialized module 'app.services.leaderboard_timer_service' (most likely due to a circular import) (C:\Users\oscar.solis\Documents\yam\app\services\leaderboard_timer_service.py)
2025-07-31 15:35:19,985 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:35:19,988 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-07-31 15:35:20,017 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:35:30,314 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:35:30] "[33mGET /api/tickets/closures/today HTTP/1.1[0m" 404 -
2025-07-31 15:36:25,406 - app - WARNING - Failed to start leaderboard timer service: cannot import name 'leaderboard_timer_service' from partially initialized module 'app.services.leaderboard_timer_service' (most likely due to a circular import) (C:\Users\oscar.solis\Documents\yam\app\services\leaderboard_timer_service.py)
2025-07-31 15:36:25,438 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:36:25,440 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-07-31 15:36:25,468 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-07-31 15:36:25,483 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.20.44.45:5000
2025-07-31 15:36:25,484 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-31 15:36:30,015 - werkzeug - INFO - 127.0.0.1 - - [31/Jul/2025 15:36:30] "[33mGET /api/tickets/closures/today HTTP/1.1[0m" 404 -
2025-08-01 07:35:36,400 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:35:36,433 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:35:36,436 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:35:36,466 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:37:14,296 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:37:14,322 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:37:14,326 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:37:14,351 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:39:07,453 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:39:07,483 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:39:07,486 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:39:07,513 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:39:52,565 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:39:52,589 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:39:52,591 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:39:52,616 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:39:52,643 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:39:52,667 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:47:13,347 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:47:13,376 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:47:13,378 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:47:13,404 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:47:22,831 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:47:22,857 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:47:22,859 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:47:22,879 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:52:24,478 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:52:24,501 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:57:25,975 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:57:25,998 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:58:58,593 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:58:58,617 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:58:58,620 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:58:58,645 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:01,921 - app - WARNING - Failed to start leaderboard timer service: 'LeaderboardTimerService' object has no attribute 'app'
2025-08-01 07:59:01,943 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:01,946 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:01,968 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:08,762 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:08,786 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:18,922 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:18,943 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:29,047 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:29,164 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:39,274 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:39,310 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:49,423 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:49,444 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
2025-08-01 07:59:59,543 - app - WARNING - Failed to start leaderboard timer service: minute must be in 0..59
2025-08-01 07:59:59,565 - app - WARNING - Blueprint registration failed: name 'chat_bp' is not defined
